BUNDLE_NAME = TweakPreferences
TweakPreferences_FILES = $(wildcard Controllers/*.m Cells/*.m)
TweakPreferences_FRAMEWORKS = UIKit
TweakPreferences_PRIVATE_FRAMEWORKS = Preferences
TweakPreferences_INSTALL_PATH = /Library/PreferenceBundles
TweakPreferences_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
